(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ClearAll["Global`*"]


(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];


(* ::Input::Initialization:: *)
Quiet[<<SBBN.m];
$EvolutionType= "SBBN"; 
TmgStart = 30.;
Ombmin=0.015;
Ombmax=0.03;
h2\[CapitalOmega]b0Array = Table[i,{i,Ombmin,Ombmax,(Ombmax-Ombmin)/(40)}];
Abundances = Table[0.,{j, 1, Length[h2\[CapitalOmega]b0Array]}];
SetSharedVariable[h2\[CapitalOmega]b0Array,Abundances];


(* ::Input::Initialization:: *)
Quiet[<<PrimiCosmo.m];
DistributeDefinitions["Global`"];

LaunchKernels[6];

ParallelDo[
Clear[h2\[CapitalOmega]b0];
h2\[CapitalOmega]b0 = h2\[CapitalOmega]b0Array[[k]];
Print["h2\[CapitalOmega]b0 = ", h2\[CapitalOmega]b0];
Quiet[<<PrimiNuc.m];
Abundances[[k]] = Join[mgresultvec[[1]],Sequence@@Flatten[List[Yf[#]&/@ShortNames]]],
{k,1,Length[h2\[CapitalOmega]b0Array]}
];

ForExport = Table[{h2\[CapitalOmega]b0Array[[l]],Sequence@@Abundances[[l]]},{l,1,Length[h2\[CapitalOmega]b0Array]}];
Export["Abundances_SBBN.txt",Join[{"Omega_b h^2     Neff       n         p         D         t         He3         a         Li7         Be7         chi2BBN         chi2CMB         chi2BBNCMB"},ForExport],"Table","FieldSeparators"->" "];
