(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
ClearAll["Global`*"]


(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];


(* ::Input::Initialization:: *)
Quiet[<<Neff.m];
$EvolutionType= "Neff"; 
h2\[CapitalOmega]b0 = 0.0225;
TmgStart = 30.1;
\[CapitalDelta]NeffArray = Array[#&,10,{0.1,1.}];
Abundances = Table[0., {i, 1, Length[\[CapitalDelta]NeffArray]}];


(* ::Input::Initialization:: *)
Do[
Clear[\[CapitalDelta]Neffective];
\[CapitalDelta]Neffective = \[CapitalDelta]NeffArray[[j]];
Print["\[CapitalDelta]Neffective = ", \[CapitalDelta]Neffective];
Quiet[<<PrimiCosmo.m];
Quiet[<<PrimiNuc.m];
Abundances[[j]] = Join[mgresultvec[[1]],Sequence@@Flatten[List[Yf[#]&/@ShortNames]]],
{j,1,Length[\[CapitalDelta]NeffArray]}
];

ForExport = Table[{Sequence@@Abundances[[k]]},{k,1,Length[\[CapitalDelta]NeffArray]}];
Export["Abundances_Neff.txt",Join[{"Neff       n         p         D         t         He3         a         Li7         Be7"}, ForExport],"Table","FieldSeparators"->" "];
