(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];
data=Import["QED_P_int.cvs","Table",HeaderLines-> 1];
Pint=Interpolation[data];
data2=Import["QED_dP_intdT.cvs","Table",HeaderLines-> 1];
dPintdT:=Interpolation[data2];
data3=Import["QED_d2P_intdT2.cvs","Table",HeaderLines-> 1];
d2PintdT2:=Interpolation[data3];


(* ::Input::Initialization:: *)
SetDirectory[NotebookDirectory[]];
data=Import["nue_ann.dat","Table",HeaderLines-> 1];
fann\[Nu]e=Interpolation[data];

data=Import["nue_scatt.dat","Table",HeaderLines-> 1];
fsca\[Nu]e=Interpolation[data];

data=Import["numu_ann.dat","Table",HeaderLines-> 1];
fann\[Nu]\[Mu]=Interpolation[data];

data=Import["numu_scatt.dat","Table",HeaderLines-> 1];
fsca\[Nu]\[Mu]=Interpolation[data];

Func[T1_,T2_]:=32 0.884*(T1^9-T2^9)+56 T1^4 T2^4*0.829*(T1-T2);

\[CapitalDelta]\[Rho]SM\[Nu]e[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_]:=   (GF^2)/\[Pi]^5 ((1+4 SW2 +8 SW2^2)(32 0.884*fann\[Nu]e[T\[Gamma]]*(T\[Gamma]^9-T\[Nu]e^9)+56 T\[Gamma]^4 *fsca\[Nu]e[T\[Gamma]]*T\[Nu]e^4*0.829*(T\[Gamma]-T\[Nu]e))+2Func[T\[Nu]\[Mu],T\[Nu]e])/.{SW2-> 0.223}/.GF-> 1.1663787 10^-11;
\[CapitalDelta]\[Rho]SM\[Nu]\[Mu][T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_]:=   (GF^2)/\[Pi]^5 ((1-4 SW2 +8 SW2^2)(32 0.884*fann\[Nu]\[Mu][T\[Gamma]]*(T\[Gamma]^9-T\[Nu]\[Mu]^9)+56 T\[Gamma]^4 *fsca\[Nu]\[Mu][T\[Gamma]]*T\[Nu]\[Mu]^4*0.829*(T\[Gamma]-T\[Nu]\[Mu]))-Func[T\[Nu]\[Mu],T\[Nu]e])/.{SW2-> 0.223}/.GF-> 1.1663787 10^-11;


(* ::Input::Initialization:: *)
me = 0.511;


(* ::Input::Initialization:: *)
(*Number and energy densities*)
nBE[T_,\[Mu]_]:=((2 T^3)/(2\[Pi]^2))PolyLog[3,E^(-(\[Mu]/T))];
nFD[T_,\[Mu]_]:=((-2 T^3)/(2\[Pi]^2)) PolyLog[3,-E^(-(\[Mu]/T))];
\[Rho]BE[T_,\[Mu]_]:=((6 T^4)/(2\[Pi]^2))PolyLog[4,E^(-(\[Mu]/T))];
\[Rho]FD[T_,\[Mu]_]:=((-6 T^4)/(2\[Pi]^2)) PolyLog[4,-E^(-(\[Mu]/T))];

nBEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
nFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];
nMBM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 NIntegrate[Enred Sqrt[Enred^2-m^2/T^2] 1/Exp[Enred-\[Mu]/T],{Enred,m/T,\[Infinity]}];
\[Rho]BEM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
\[Rho]FDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^4 NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];
pBEM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) T^4 NIntegrate[(Enred^2-m^2/T^2)^(3/2) 1/(Exp[Enred-\[Mu]/T]-1),{Enred,m/T,\[Infinity]}];
pFDM[T_,\[Mu]_,m_]:=1/(6 \[Pi]^2) T^4 NIntegrate[(Enred^2-m^2/T^2)^(3/2) 1/(Exp[Enred-\[Mu]/T]+1),{Enred,m/T,\[Infinity]}];

d\[Rho]dTFDM[T_,\[Mu]_,m_]:=1/(2 \[Pi]^2) T^3 Quiet[NIntegrate[Enred^2 Sqrt[Enred^2-m^2/T^2] ((Enred -\[Mu]/T) Sech[(Enred -\[Mu]/T)/2]^2)/4 ,{Enred,m/T,\[Infinity]}]];
Partial\[Gamma]e[T_]:=2 (2 \[Pi]^2 T^3)/15+4d\[Rho]dTFDM[T,0,me]+T d2PintdT2[T] ;


Hubble[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]_,MZ_]:= \[Sqrt]((2 \[Rho]BE[T\[Gamma],0]+4\[Rho]FDM[T\[Gamma],0,me]+2\[Rho]FD[T\[Nu]e,0]+4\[Rho]FD[T\[Nu]\[Mu],\[Mu]\[Nu]]-Pint[T\[Gamma]]+T\[Gamma] dPintdT[T\[Gamma]]) (8 \[Pi])/(3 (1.2209 10^19 10^3)^2));

\[Rho]tot[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]_,MZ_]:=(2 \[Rho]BE[T\[Gamma],0]+4\[Rho]FDM[T\[Gamma],0,me]+2\[Rho]FD[T\[Nu]e,0]+4\[Rho]FD[T\[Nu]\[Mu],\[Mu]\[Nu]]);

ptot[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]_,MZ_]:=(1/3 2 \[Rho]BE[T\[Gamma],0]+4pFDM[T\[Gamma],0,me]+1/3 2\[Rho]FD[T\[Nu]e,0]+4 1/3 \[Rho]FD[T\[Nu]\[Mu],\[Mu]\[Nu]]);

RHSec[T\[Gamma]_,T\[Nu]e_,T\[Nu]\[Mu]_,\[Mu]\[Nu]_,MZ_]:=-3 Hubble[T\[Gamma],T\[Nu]e,T\[Nu]\[Mu],\[Mu]\[Nu],MZ](\[Rho]tot[T\[Gamma],T\[Nu]e,T\[Nu]\[Mu],\[Mu]\[Nu],MZ]+ ptot[T\[Gamma],T\[Nu]e,T\[Nu]\[Mu],\[Mu]\[Nu],MZ]);



(* ::Input::Initialization:: *)
m0=me;
dz\[Gamma]dt[z\[Gamma]_,z\[Nu]e_,z\[Nu]\[Mu]_,\[Mu]\[Nu]_,g_,MZ_,a_]:=z\[Gamma]/a (1/(z\[Gamma] m0/a *Partial\[Gamma]e[z\[Gamma] m0/a]) (z\[Gamma] m0/a *Partial\[Gamma]e[z\[Gamma] m0/a]-4*2*\[Rho]BE[z\[Gamma] m0/a,0]-3*4(\[Rho]FDM[z\[Gamma] m0/a,0,me]+pFDM[z\[Gamma] m0/a,0,me])-3*z\[Gamma] m0/a dPintdT[z\[Gamma] m0/a]-( \[CapitalDelta]\[Rho]SM\[Nu]e[z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a]+2 \[CapitalDelta]\[Rho]SM\[Nu]\[Mu][z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a])/Hubble[z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a,0,0]));

dz\[Nu]edt[z\[Gamma]_,z\[Nu]e_,z\[Nu]\[Mu]_,\[Mu]\[Nu]_,g_,MZ_,a_]:=z\[Nu]e/a (\[CapitalDelta]\[Rho]SM\[Nu]e[z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a]/(4 Hubble[z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a,0,0]*2*\[Rho]FDM[z\[Nu]e m0/a,0,0]));

dz\[Nu]\[Mu]dt[z\[Gamma]_,z\[Nu]e_,z\[Nu]\[Mu]_,\[Mu]\[Nu]_,g_,MZ_,a_]:= z\[Nu]\[Mu]/a (\[CapitalDelta]\[Rho]SM\[Nu]\[Mu][z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a]/(4 Hubble[z\[Gamma] m0/a,z\[Nu]e m0/a,z\[Nu]\[Mu] m0/a,0,0]*2*\[Rho]FDM[z\[Nu]\[Mu] m0/a,0,0]));



(* ::Input::Initialization:: *)
FuncSMnudec[T\[Nu]0_]:=(
a0=m0/T\[Nu]0;
amax=m0/0.01;(* Tnu ~= 0.01 MeV, a time at which e+e- have annihilated away *)

solEarlyUniverse=NDSolve[{ 
z\[Gamma]'[a]==dz\[Gamma]dt[z\[Gamma][a],z\[Nu][a],z\[Nu][a],0,0,0,a],z\[Nu]'[a]==1/3 (dz\[Nu]edt[z\[Gamma][a],z\[Nu][a],z\[Nu][a],0,0,0,a]+2dz\[Nu]\[Mu]dt[z\[Gamma][a],z\[Nu][a],z\[Nu][a],0,0,0,a]),
z\[Gamma][a0]==1,z\[Nu][a0]==1},{z\[Gamma],z\[Nu]},{a,a0,amax},PrecisionGoal->8,AccuracyGoal->8];

Neffres=(8/7 (11/4)^(4/3) (4 \[Rho]FD[z\[Nu][a],0]+2 \[Rho]FD[z\[Nu][a],0])/(2\[Rho]BE[z\[Gamma][a],0])/.solEarlyUniverse/.{a-> amax})[[1]]//N;

z\[Gamma]res=(z\[Gamma][a]/.solEarlyUniverse/.{a-> amax})[[1]];
z\[Nu]res=(z\[Nu][a]/.solEarlyUniverse/.{a-> amax})[[1]];

NaParthenope[a1_]:=((4/z\[Gamma][a]^4 7/8 \[Pi]^2/15 ( 3 a/z\[Nu][a] D[z\[Nu][a],a]))/.solEarlyUniverse/.a-> a1)[[1]];

{Neffres,z\[Gamma]res,z\[Nu]res,(z\[Gamma][a]/.solEarlyUniverse)[[1]],(z\[Nu][a]/.solEarlyUniverse)[[1]],NaParthenope[a]});



